version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nola-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: ["bun", "run", "dev"]
    networks:
      - nola-net

  db:
    image: postgres:16
    container_name: nola-db
    restart: always
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge_2024
      POSTGRES_DB: challenge_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - nola-net

networks:
  nola-net:
    driver: bridge

volumes:
  db_data:
